
on:
   push:
     branches: [ main, develop ]
     paths-ignore:
       - 'templates/**'
       - 'config/**'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Pushes to all staging sites
         run: |
           git fetch
           git checkout develop
           git pull
           git checkout -b staging/UK
           git merge develop
           git push -f --set-upstream origin staging/UK

