
name: Staging Setup

on:
  push:
    branches: [ develop ]

jobs:
  staging-us-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
        with:
          ref: production/us

      - name: Checkout or Create staging-us from prod
        run: git checkout -b staging/us

      - name: Get Templates/Config from production
        run: |
          rm templates/*.json
          rm templates/**/*.json
          rm config/*.json
          git checkout -f staging/us templates/*.json
          git checkout -f staging/us templates/**/*.json
          git checkout -f staging/us config/*.json
          git config --global user.name "staging-automation"
          git config --global user.email "qa.automation+staging@pela.earth"
          git commit -a -m "Back Merge Content From Production"

      - name: Merge Dev into staging, keeping dev while not committing
        run: git merge -s theirs -no-commit develop 

      - name: Reset Templates and Config
        run: |
          git checkout -f HEAD templates/*.json
          git checkout -f HEAD templates/**/*.json
          git checkout -f HEAD config*.json

      - name: Make merge Commit
        run: git commit -a -m "Merge dev into staging (not including templates/config)"

      - name:
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Release, US"
          body: "Release, US"












